@baseUri=http://127.0.0.1:8014/api 

### gen video
POST {{baseUri}}/gen-video
Content-Type: application/json

{
    "description": "spider man fighting with iron man"
}

### update videos
POST {{baseUri}}/process/update-videos
Content-Type: application/json