import { Video } from "@/types/Video";

export default function ({ videos }: { videos: Video[] }) {
  return (
    <section>
      <div className="mx-auto w-full max-w-7xl px-5 py-16 md:px-10 md:py-24 lg:py-32">
        <h2 className="mb-6 text-primary text-center text-3xl font-bold md:mb-12 md:text-5xl">
          AI Videos Generated by Sora
        </h2>
        <ul className="grid items-center justify-items-center gap-8 sm:gap-20 lg:grid-cols-3">
          {videos.map((video: Video, idx: number) => {
            return (
              <li key={idx}>
                <video
                  className="video w-full cursor-pointer"
                  src={video.video_url}
                  poster={video.cover_url}
                  preload="auto"
                  muted
                  loop
                  controls
                  autoPlay
                >
                  Your browser does not support the video tag.
                </video>

                <p className="mt-4 max-w-lg">{video.description}</p>
              </li>
            );
          })}
        </ul>
      </div>
    </section>
  );
}
